### ISSUE TITLE
Max retries exceeded with url: /api/alexa/smart_home

### ISSUE THREAD

**Issue by idorose** [mike-grant/haaska#92] opened 2019-01-29 11:07 UTC
I just installed HAASKA
after finishing the setup according to "The Wanderer" guide, I ran the test script and got:

errorMessage": "HTTPSConnectionPool(host='xxxxxxxx.myqnapcloud.com', port=443): Max retries exceeded with url: /api/alexa/smart_home (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

I'm using HA on docker container on a QNAP nas,

when going to https://xxxxxxxx.myqnapcloud.com/api/ I get the 401 message and on
https://xxxxxxxx.myqnapcloud.com/api/alexa/smart_home I get the 405 message

browsing to HA with HTTPS on chrome is also fine

any idea what's wrong?

**Comment by anthonylavado** [comment] 2019-01-29 23:50
@idorose Hey there! :wave: 
Could you post what your config.json looks like? Remember to take out the bits of the long lived token.

Thanks!

**Comment by anthonylavado** [comment] 2019-01-31 03:45
Hrm... is your certificate self signed, or is it from Let’s Encrypt?

Basically the SSL Verify part of your config asks the Haaska code to compare what you’ve got, to a well known list of providers. If it’s not in the list (like a self signed certificate), then it will fail. At that point, you’d probably need to set SSL verify to off.

I know you can probably add it in ssl_client, but I’m not sure how that works.

**Comment by idorose** [comment] 2019-01-31 06:00
its lets encrypt but it wasnt generated by the usual procedure, it was
generated by my NAS and then i had to use an online tool to convert its
format

**Comment by anthonylavado** [comment] 2019-02-03 19:44
If you both try with ssl verify set to false, does it work?

**Comment by tarat73** [comment] 2019-02-03 19:59
No. It is the same...

Response:
{
  "errorMessage": "HTTPSConnectionPool(host='XXXXXXXXX.org', port=8123): Max retries exceeded with url: /api/alexa/smart_home (Caused by SSLError(SSLError(336265225, '[SSL] PEM lib (_ssl.c:3520)'),))",
  "errorType": "SSLError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      109,
............

**Comment by idorose** [comment] 2019-02-03 20:08
for me it worked

**Comment by tarat73** [comment] 2019-02-03 20:32
I tried without ssl...
It works..

{
"url": "http://xxxxxxxx:8123/api",
"debug": true,
"ssl_verify": false,
"bearer_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}


  esponse:
{
  "event": {
    "header": {
      "messageId": "a8f53eee-7ae6-4d2c-b4a6-4bc9aebd53b7",
      "name": "Discover.Response",
      "namespace": "Alexa.Discovery",

but I have problem with ssl...

**Comment by anthonylavado** [comment] 2019-02-04 08:06
All, I fixed up the formatting to make it easier to read. I hope you don't mind.

---

@tarat73 Change your `config.json` to be like this:
```json
{
  "url": "https://xxxxxxxx:8123/api",
  "debug": true,
  "ssl_verify": true,
  "ssl_client": [],
  "bearer_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}
```

In other words, remove the .crt from the "ssl_client". I still don't understand that setting very much, but I'll ask about it (#77).

---

@idorose It's definitely something strange about your certificate then. You said you had to convert it... Are there steps you can share? A website with instructions? I'll need to know what happened to it.

**Comment by tarat73** [comment] 2019-02-04 08:13
Unfortunately it doesn't work...

{
  "url": "https://XXXXXX.org:8123/api",
  "debug": true,
  "ssl_verify": true,
  "ssl_client": [],
  "bearer_token": "XXXXXXXXXXXXXX"
}

result:

Response:
{
  "errorMessage": "HTTPSConnectionPool(host='tarat.hopto.org', port=8123): Max retries exceeded with url: /api/alexa/smart_home (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))",
  "errorType": "SSLError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      109,
      "event_handler",
.........

**Comment by TheZoker** [comment] 2019-02-06 15:59
@tarat73 My guess would be, that the port is wrong. 

According to [this instruction](http://collingwood.me.uk/blog/index.php/hass-io-and-alexa/) (point 4.) you can't use port 8123, but only 443. So you need to create a port forwarding from 443 to 8123 within your router.

Then remove the port from the haaska config file

**Comment by anthonylavado** [comment] 2019-02-06 17:07
@thezoker Saw your post on the forums. Haven’t replied yet (working). In short, I believe that AWS Lambda doesn’t support IPv6, though I could be wrong.

**Comment by glassbase** [comment] 2019-02-10 17:59
I was having this issue too. 

I had to put `:443` like so `"url": "https://home.mydomain.ca:443/api",`. It did not work as `"url": "https://home.mydomain.ca/api",` - which makes no sense?!

**Comment by anthonylavado** [comment] 2019-02-16 05:12
Okay - closing this to have separate issues. Will reference them out.

**Closed by anthonylavado** 2019-02-16 05:12 UTC

**Comment by pippo73** [comment] 2020-09-28 14:38
I'm experiencing a similar problem. Should I open a new issue or you could reopen this one?
I have a self generated SSL certification, validate by zerossl.
If I set ssl to true it gives me the error, if it is set to false it goes ok.

**Comment by mike-grant** [comment] 2020-09-28 20:57
@pippo73 a new issue would be preferred than re-opening an old issue. However, if you're using a self signed SSL certificate, then you will need to set SSL to false, otherwise your certificate will fail the validation.

**Comment by pippo73** [comment] 2020-09-29 07:25
it is not a self signed. I've created the privat key, but I use zerossl as certification autority
