### ISSUE TITLE
Max retries exceeded with url: /api/alexa/smart_home

### ISSUE THREAD

**Issue by chimpy** [mike-grant/haaska#58] opened 2018-10-28 00:29 UTC
Hello,

Sorry to bother you with this issue but I have tried everything and have no wtf I have this error when I execute the test snippet. Please help, my brain hurts!

- haaska skill language is English (UK).
- Lambda region is Ireland.
- Endpoint: arn:aws:lambda:eu-west-1:amazonID:function:haaska
- Client ID/Client Secret/Redirect URLs configured.
- Skill ID entered in function
- Haaska Config:

```
{
  "url": "https://hass.mydomain.com/api",
  "bearer_token": "my_token",
  "debug": false,
  "ssl_verify": false,
  "ssl_client": []
}
```

- Hass config:

```
alexa:
  smart_home:
    entity_config:
      light.living_room:
        name: Ceiling
      light.reading:
        name: Reading
      light.bathroom_lights:
        name: Ceiling
      light.bedroom_main:
        name: Ceiling
      light.bedroom_strip:
        name: Headboard
etc.
```

Error:

```
{
  "errorMessage": "HTTPSConnectionPool(host='hass.mydomain.com', port=443): Max retries exceeded with url: /api/alexa/smart_home (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7faa2be26f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))",
  "errorType": "ConnectionError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      109,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True).json()"
    ],
    [
      "/var/task/haaska.py",
      62,
      "post",
      "timeout=(None, read_timeout))"
    ],
    [
      "/var/task/requests/sessions.py",
      572,
      "post",
      "return self.request('POST', url, data=data, json=json, **kwargs)"
    ],
    [
      "/var/task/requests/sessions.py",
      524,
      "request",
      "resp = self.send(prep, **send_kwargs)"
    ],
    [
      "/var/task/requests/sessions.py",
      637,
      "send",
      "r = adapter.send(request, **kwargs)"
    ],
    [
      "/var/task/requests/adapters.py",
      516,
      "send",
      "raise ConnectionError(e, request=request)"
    ]
  ]
}
```

**Comment by anthonylavado** [comment] 2018-10-28 06:39
@chimpy Hey there.
If you go to "https://haas.mydomain.com/api/" (obviously with your actual domain in there), do you get anything back? It should be a "401: Unauthorized".

Similarly, if you manually browse to "https://haas.mydomain.com/api/alexa/smart_home", you should get a "405: Method Not Allowed".

**Comment by chimpy** [comment] 2018-10-28 07:09
Hey mike,

Thanks for the reply!

I get 404 for the API and 405 for api/alexa/smart_home.

I don’t understand why api would throw a 404... any ideas?

Thanks!

**Comment by anthonylavado** [comment] 2018-10-28 08:15
@chimpy Hey there again. (As a note, this is Anthony, not Mike. I handle most of the issues, as well as write the Documentation and Wiki).

Unfortunately, I'm not sure where the issue could be in API giving you the 404. It certainly means that that there's a communication issue somewhere, and this is why the Lambda function is having trouble. It needs to be able to reach that page as well in order to login.

I would start by double checking all your port forwards/instructions and go from there.

**Comment by chimpy** [comment] 2018-10-28 08:31
@anthonylavado Apologies for that...was replying by mail and just got up :/

I just checked the URLs again and this time I'm getting a 403 on both.

What's weird is that all my other stuff is working: Homekit, Google Assistant, LIFX, Lightify, Xiaomi. It's all working with no problems. Apart from the Lambda function. This is on 0.81 btw. Apart from creating a LLAT for the new auth system to work, is there anything else I should have done?

Thanks again.

**Comment by chimpy** [comment] 2018-10-28 11:55
@anthonylavado Ah sorry! I was entering hass.domain.com/api - without the slash. hass.domain.com/api/ gives me back a 401 as you say it should.

Again, to resume:

/api/ gives 401.
/api/alexa/smart_home gives 405.

**Comment by anthonylavado** [comment] 2018-10-30 06:12
@chimpy I’m really sorry, but I don’t know where to go further from here. https is definitely the way to go, and the Haaska code adds the slash for you, so it looks like you’ve done everything correctly.

My last two thoughts:
- Do you need a port number for Home Assistant? My URL for example: “https://myhass.example.com:8123/api”
- Can your HA install be reached from the internet? If not, you might need to add port forwarding on your router (but it sounds like this is working already)

**Comment by jaburges** [comment] 2018-10-31 18:39
Hi there, 
I'm getting the same in the test output.
Now I use synology which uses a reverse proxy (just an inbuilt NGINX). 

I can browse to http://HA_URL/api/ and get 401 unauthorized and i'm getting unauthorized attempt from local IP (but not anything in the log from AWS).
I use a wild card cert in the Synology reverse proxy - which leads me to wonder as this request isnt coming from the expected URL that the cert is tied to NGINX isnt allowing it through. 

Apologies, i'm not great with certs - just enough to get HA running on a custom domain with a wildcard.
Which cert file is needed, and where would the best place be to put it (and referenced in the config.json)
appreciate any help!

**Comment by anthonylavado** [comment] 2018-10-31 19:00
@jaburges See this other issue: https://github.com/mike-grant/haaska/issues/59

**Comment by jaburges** [comment] 2018-11-01 00:07
thanks @anthonylavado my apologies (i've been trying to troubleshoot and assumed it was something it wasnt)

I'm a little confused by the difference between alexa cloud and alexa.
Cloud:
```
cloud:
  alexa:
    filter:
      [stuff]
```
Alexa:
```
alexa:
  smart_home:
    filter:
      [stuff]
```

I get 404 on the http://URL/api/alexa/smart_home/
is there anyway to troubleshoot whether the issue is cloud, my edge/perimeter or HA itself?

**Comment by anthonylavado** [comment] 2018-11-01 00:45
@jaburges - For Haaska, you must use the Smart Home API, which is the second example you listed. The one that begins with `alexa:`.

The cloud one is only for when you use the official, paid cloud connector from Nabu Casa/Home Assistant.

Once the Smart Home API is in your config, the API URL (“.../api/alexa/smart_home”) should show error 405. Once that is working, then Haaska can discover your devices and work.

Let me know if I can help with anything else :smile:

**Comment by jaburges** [comment] 2018-11-01 00:53
Thats the thing - i have enabled the latter, and not getting 405. (and also big thanks for your help with this).

I'm just rebuilding to see if using https://URL/api and the ssl verify with the cert will solve it, but I cant help coming back to the fact that i'm not getting 405 using the URL.

I'm using a public hosted URL with a wildcard cert (as use subdomains for specific services) - forwards to public IP on router, router port forwards to synology box, NGINX reverse proxy forwards to specific ports (as the services are in docker containers) from specific subdomains. ie 
HA.URL.com [80] > public IP [80] > synologyIP [80] > NGINX synology [8123] (same deal for 443)

any other way to check if smart_home api is functioning? GET or POST to it directly?

**Comment by anthonylavado** [comment] 2018-11-01 01:17
@jaburges - Trying to load the page is the same as doing a GET, so if that isn’t working, it’s definitely a communication issue somewhere along the way. Is there any way you can try loading the URL with the internal IP address for Home Assistant?

**Comment by jaburges** [comment] 2018-11-01 01:35
ok think i've found it. in moving from alexa / cloud to alexa / smart_home i used 
```alexa: !include dir/alexa.yaml```

i've noticed that some HA components are fussy (or i'm simply not formulating it correctly in the file.yaml)
moving this directly to the config.yaml the test passes. 
now to move it to https:// with the cert 
thanks again for the help!

**Comment by jaburges** [comment] 2018-11-01 01:43
also i cant confirm (trying to) but it seems like the error also appears when both
```
cloud:
```
and
```
alexa:
``` 
are enabled

**Comment by jaburges** [comment] 2018-11-01 01:55
> Hey mike, Thanks for the reply! I get 404 for the API and 405 for api/alexa/smart_home. I don’t understand why api would throw a 404... any ideas? Thanks!
> […](#)
> On 28 Oct 2018, at 07:39, Anthony Lavado ***@***.***> wrote: @chimpy Hey there. If you go to "https://haas.mydomain.com/api/" (obviously with your actual domain in there), do you get anything back? It should be a "401: Unauthorized". Similarly, if you manually browse to "https://haas.mydomain.com/api/alexa/smart_home", you should get a "405: Method Not Allowed". — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

so been messing around with this. Check 3 things:
1. the URL matches your EXTERNAL url http://blah.domain.suffix/api (you may need port 8123)
2. if you need port 8123 in your URL make sure you have port forwarding for that port
3. check if both cloud alexa and alexa smart_home are both enabled
4. if you use !include to split out your config - put all the alexa contents in the config.yaml

Anyway hope this helps someone who finds it

**Comment by esabea** [comment] 2018-11-02 12:48
sorry.....I have this error and I do not know how to solve it (I have tried many things already ...)

My config.json is this

{
  "url": "https://myhost/api",
  "bearer_token": "My Long-Lived token",
  "debug": true,
  "ssl_verify": true,
  "ssl_client": "fullchain.pem" -> ssl_certificate of configuration.yaml (located in the same directory of config.json)
}

this is muy "test" of lambda function

{
  "directive": {
    "header": {
      "namespace": "Alexa.Discovery",
      "name": "Discover",
      "payloadVersion": "3",
      "messageId": "1bd5d003-31b9-476f-ad03-71d471922820"
    },
    "payload": {
      "scope": {
        "type": "BearerToken",
        "token": "My Long-Lived token"
      }
    }
  }
}

and this is the results when I execute 

Response:
{
  "errorMessage": "HTTPSConnectionPool(host='[myhost]', port=443): Max retries exceeded with url: /api/alexa/smart_home (Caused by SSLError(SSLError(336265225, '[SSL] PEM lib (_ssl.c:3309)'),))",
  "errorType": "SSLError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      109,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True).json()"
    ],
    [
      "/var/task/haaska.py",
      62,
      "post",
      "timeout=(None, read_timeout))"
    ],
    [
      "/var/task/requests/sessions.py",
      572,
      "post",
      "return self.request('POST', url, data=data, json=json, **kwargs)"
    ],
    [
      "/var/task/requests/sessions.py",
      524,
      "request",
      "resp = self.send(prep, **send_kwargs)"
    ],
    [
      "/var/task/requests/sessions.py",
      637,
      "send",
      "r = adapter.send(request, **kwargs)"
    ],
    [
      "/var/task/requests/adapters.py",
      514,
      "send",
      "raise SSLError(e, request=request)"
    ]
  ]
}

Request ID:
"1051387e-de9d-11e8-bc7b-81abac981004"

Function Logs:
START RequestId: 1051387e-de9d-11e8-bc7b-81abac981004 Version: $LATEST
[DEBUG]	2018-11-02T12:44:40.1Z	1051387e-de9d-11e8-bc7b-81abac981004	calling alexa/smart_home with {'directive': {'header': {'namespace': 'Alexa.Discovery', 'name': 'Discover', 'payloadVersion': '3', 'messageId': '1bd5d003-31b9-476f-ad03-71d471922820'}, 'payload': {'scope': {'type': 'BearerToken', 'token': '[my token]'}}}}
[DEBUG]	2018-11-02T12:44:40.3Z	1051387e-de9d-11e8-bc7b-81abac981004	Starting new HTTPS connection (1): [myhost]:443
HTTPSConnectionPool(host='[myhost]', port=443): Max retries exceeded with url: /api/alexa/smart_home (Caused by SSLError(SSLError(336265225, '[SSL] PEM lib (_ssl.c:3309)'),)): SSLError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 109, in event_handler
    return ha.post('alexa/smart_home', event, wait=True).json()
  File "/var/task/haaska.py", line 62, in post
    timeout=(None, read_timeout))
  File "/var/task/requests/sessions.py", line 572, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/task/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/task/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/var/task/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='[myhost]', port=443): Max retries exceeded with url: /api/alexa/smart_home (Caused by SSLError(SSLError(336265225, '[SSL] PEM lib (_ssl.c:3309)'),))

END RequestId: 1051387e-de9d-11e8-bc7b-81abac981004
REPORT RequestId: 1051387e-de9d-11e8-bc7b-81abac981004	Duration: 258.31 ms	Billed Duration: 300 ms 	Memory Size: 128 MB	Max Memory Used: 29 MB	

and the last.....the configuration.yaml is

alexa:
  smart_home:
    filter:
      include_entities:
        - light.xxxxx
        - sensor.xxxx
    entity_config:
      light.xxxxx
        name: name of light
        description: description of light
        display_categories: LIGHT
      sensor.xxxxx:
        name: name of sensor
        description: description of sensor
        display_categories: TEMPERATURE_SENSOR 
		
		
Can help me?

**Comment by anthonylavado** [comment] 2018-11-02 13:12
@esabea - Hey there! Use `cert.pem` instead of `fullchain.pem`.

**Comment by esabea** [comment] 2018-11-02 13:19
> @esabea - Hey there! Use `cert.pem` instead of `fullchain.pem`.

nothing .... the result is the same "Max retries exceeded with url: /api/alexa/smart_home"

**Comment by esabea** [comment] 2018-11-02 15:49
if I use this config.json

`{
  "url": "https://[myhost]/api",
  "bearer_token": "[long token]",
  "debug": true,
  "ssl_verify": false,
  "ssl_client": []
}
`

I view a Login attempt in HA UI from a IP (Amazon)

I checked that the token is correct doing this

`curl -X GET \
  https://[myhost]/api/error/all \
  -H 'Authorization: Bearer [token]'`

and this if it works

**Comment by anthonylavado** [comment] 2018-11-02 18:39
@esabea - Ok. I will be testing this myself tonight. 

I normally use it with SSL Verify false, so I will try turning that on with my certificate too.

**Comment by esabea** [comment] 2018-11-02 19:40
> @esabea - Ok. I will be testing this myself tonight.
> 
> I normally use it with SSL Verify false, so I will try turning that on with my certificate too.


do not worry ... I have managed to solve the simplest way in the world, repeating everything from the beginning!

**Comment by anthonylavado** [comment] 2018-11-03 03:46
Thanks to all who troubleshooted in this thread. Apologies to @chimpy as it got a bit cluttered.

Closing for now. If anyone needs help, please open a new issue.

**Closed by anthonylavado** 2018-11-03 03:46 UTC
Labels: question

**Comment by itajackass** [comment] 2019-01-06 00:16
Until today all working great. But today I decided to buy a new router (fritz box 7530). I've set same SSID, same password, same statics ip... And lambda test get error like this post. What can be the problem?

**Comment by anthonylavado** [comment] 2019-01-06 00:39
Hi @itajackass,
It’s usually best to make a new issue. I’ll open one now.
